#关于GateWay的配置请参考文档http://cloud.spring.io/spring-cloud-gateway/single/spring-cloud-gateway.html
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:19000/eureka/
#端口的使用请参考端口设计文档
server:
  port: 19099
spring:
  application:
    name: lotion-web-gateway
  cloud:
    stream:
      #指定用kafka stream来作为默认消息中间件
      default-binder: kafka
      kafka:
        binder:
          brokers: 47.106.222.205:9092
    #gateway
    #目前的gateway暂时还没有类似zuul ignore-patterns可以过滤形如/**/actuator/**请求的过滤器，需要进行如下配置
    #默认集群内lb://serviceId;兼容websocket，ws://url;两者混合使用lb:ws://serviceId
    gateway:
      #放开本地前后端分离开发的跨域访问权限
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "localhost"
            allowedMethods:
            - GET
            - POST
      default-filters:
      #hystrix过滤器
      - name: Hystrix
        args:
          name: fallback
          fallbackUri: forward:/fallback
      #SaveSessiong过滤器
      #Spring Security结合Spring Seesion时使用
      #- SaveSession
      routes:
      #/actuator/**映射到本地
      - id: local-actuator
        uri: forward:///actuator
        predicates:
        - Path=/actuator/**
        filters:
        #Strip过滤器
        - StripPrefix=1
      #拒绝/**/actuator/**路由
      - id: local-actuator-reject
        uri: forward:///reject
        predicates:
        - Path=/**/actuator/**
      #webuis
      - id: web-webuis
        uri: lb://lotion-web-webuis
        predicates:
        - Path=/webuis/**
        filters:
        #Strip过滤器
        - StripPrefix=1
      #supervision
      - id: web-webuis
        uri: lb://lotion-web-supervision
        predicates:
        - Path=/supervision/**
        filters:
        #Strip过滤器
        - StripPrefix=1
      #control
      - id: web-control
        uri: lb://lotion-web-control
        predicates:
        - Path=/control/**
        filters:
        #Strip过滤器
        - StripPrefix=1
      #log
      - id: web-log
        uri: lb://lotion-web-log
        predicates:
        - Path=/log/**
        filters:
        #Strip过滤器
        - StripPrefix=1
      #index
      #存在映射顺序问题，index必须放在最后，因为是按照顺序遍历的
      - id: web-index
        uri: lb://lotion-web-index
        predicates:
        - Path=/**
        filters:
      discovery:
        locator:
          #启动与eureka结合
          enabled: true
          #serviceId小写
          lower-case-service-id: true
#设置hystrix断路超时时间为60秒，防止由于过短的超时时间导致网页加载未完成就断路
hystrix.command.fallback.execution.isolation.thread.timeoutInMilliseconds: 60000
#默认hystrix请求超时时间60秒
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
#默认ribbon请求连接超时时间2秒
ribbon.ConnectTimeout: 2000
#默认ribbon请求读取超时时间20秒
ribbon.ReadTimeout: 20000
#默认ribbon请求可以重试
ribbon.OktoRetryOnAllOperations: true
#默认ribbon请求对当前实例重试次数为1
ribbon.MaxAutoRetries: 1
#默认ribbon请求切换实例重试次数为1
ribbon.MaxAutoRetriesNextServer: 1
#启动所有映射(默认只有../actuator/health和../actuator/info)
management:
  endpoints:
    web:
      exposure:
        include: '*'