eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:19000/eureka/
#端口的使用请参考端口设计文档
server:
  port: 19003
spring:
  application:
    name: lotion-dao-mongo

  data:
    mongodb:
      uri: mongodb://47.106.222.205:27017/mongo