eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:19000/eureka/
#端口的使用请参考端口设计文档
server:
  port: 19081
spring:
  application:
    name: lotion-web-webuis
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
  cloud:
    stream:
      #指定用kafka stream来作为默认消息中间件
      default-binder: kafka
      kafka:
        binder:
          brokers: 47.106.222.205:9092
  mvc:
    static-path-pattern: /**
#开启log4j2日志
logging:
  config: classpath:log4j2.yml
#开启feign与hystrix联动
feign:
  hystrix:
    enabled: true
#启动所有映射(默认只有../actuator/health和../actuator/info)
#可以解决hystrix.stream的映射问题默认在../actuator/hystrix.stream
management:
  endpoints:
    web:
      exposure:
        include: '*'
#默认hystrix请求超时时间60秒
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
#自定义配置
custom:
  eureka-url: http://127.0.0.1:19000
  hbase-url: http://127.0.0.1:60010
  hdfs-url: http://127.0.0.1:9000
  hystrix-url: http://127.0.0.1:19031/hystrix
  kafka-url: http://127.0.0.1:8089
  spark-url: http://127.0.0.1:8090
  yarn-url: http://127.0.0.1:8088
  zookeeper-url: http://127.0.0.1:10000