eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:19000/eureka/
#端口的使用请参考端口设计文档
server:
  port: 19098
spring:
  application:
    name: lotion-web-login
    security:
      basic:
        enabled: true    #启用SpringSecurity的安全配置项
      user:
        name: root    #认证用户名
        password: Qinjibo123 #认证密码
        role:
  cloud:
      stream:
        #指定用kafka stream来作为默认消息中间件
        default-binder: kafka
        kafka:
          binder:
            brokers: 47.106.222.205:9092

#开启log4j2日志
logging:
  config: classpath:log4j2.yml
#开启feign与hystrix联动
feign:
  hystrix:
    enabled: true
#启动所有映射(默认只有../actuator/health和../actuator/info)
#可以解决hystrix.stream的映射问题默认在../actuator/hystrix.stream
management:
  endpoints:
    web:
      exposure:
        include: '*'
#默认hystrix请求超时时间60秒
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000